# Utilizamos la imagen de Node.js como base
FROM node:16

# Instalamos Angular CLI globalmente
RUN npm install -g @angular/cli@16

# Establecemos un directorio de trabajo para la aplicación
WORKDIR /app
